version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  nats:
    image: nats-streaming:0.24.6
    container_name: nats
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - nats-streaming
      - "--clustered"
      - "--cluster_bootstrap"
      - "--cluster_log_path"
      - /data/log
      - "--cluster_node_id"
      - nats-streaming-1
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - /data/msg
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--store"
      - file
      - "--stan_debug"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    ports:
      - "4222:4222"
      - "8222:8222"
    expose:
      - "4222"
      - "8222"
    restart: always

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  
  user:
    image: user
    build: 
      context: ./user
      dockerfile: Dockerfile-dev
    container_name: user
    volumes:
      - ./user/src:/usr/src/app/src
      # - ./user/nodemon.json:/usr/src/app/nodemon.json
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/user
      - REDIS_URL=redis:6379
      - NATS_CLUSTER_ID=nats-streaming
      - NATS_CLIENT_ID=agretwg
      - NATS_URL=nats://nats:4222
      - JWT_KEY=secretbdjeflawhcvdeqafecvrkepqofv
    depends_on:
      - nats
      - db
      - redis
    restart: "no"

  question:
    image: question
    build: 
      context: ./question
      dockerfile: Dockerfile-dev
    container_name: question
    volumes:
      - /tmp/question/npm-cache:/root/.npm:z
      - ./question/src:/usr/src/app/src:z
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - NODE_ENV=development
      - MONGO_URI=mongodb://db:27017/question
      - REDIS_URL=redis:6379
      - NATS_CLUSTER_ID=nats-streaming
      - NATS_CLIENT_ID=alsdkjfdne3jkwl1f
      - NATS_URL=nats://nats:4222
      - JWT_KEY=secretbdjeflawhcvdeqafecvrkepqofv
    depends_on:
      - nats
      - db
      - redis
    restart: "no"
  
  fanout:
    image: fanout
    build: 
      context: ./fanout
      dockerfile: Dockerfile-dev
    container_name: fanout
    volumes:
      - /tmp/fanout/npm-cache:/root/.npm:z
      - ./fanout/src:/usr/src/app/src:z
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - NATS_CLUSTER_ID=nats-streaming
      - NATS_CLIENT_ID=alsdkj
      - NATS_URL=nats://nats:4222
      - JWT_KEY=secretbdjeflawhcvdeqafecvrkepqofv
    depends_on:
      - nats
      - db
      - redis
    restart: "no"
  
  timeline:
    image: timeline
    build: 
      context: ./timeline
      dockerfile: Dockerfile-dev
    container_name: timeline
    volumes:
      - /tmp/timeline/npm-cache:/root/.npm:z
      - ./timeline/src:/usr/src/app/src:z
    ports:
      - "4004:4004"
    environment:
      - PORT=4004
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - JWT_KEY=secretbdjeflawhcvdeqafecvrkepqofv
      # - MONGO_URI=mongodb://db:27017/question
    depends_on:
      - redis
      - db
    restart: "no"
  